server:
  port: 8082
  contextPath: /
  address: 0.0.0.0

etcdUrl: http://10.60.38.51:4001

spring:
   datasource:
     url: jdbc:mysql://10.4.4.202:3306/gateway?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&failOverReadOnly=false&autoReconnect=true
     username: root
     password: 123123
     dbcp2:
       driver-class-name: com.mysql.jdbc.Driver

mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mappers/*.xml


logging:
    level:
        root: info
        org.springframework.boot: info
        org.apache.ibatis: info
        com.jwcjlu.skyway.bonuspoint: info
        com.jwcjlu.skyway.lottery: debug
        com.jwcjlu.skyway: debug

     path: "./logs/admin"

roleDataId: 1
pluginRawData: 3,4,7,8,109,114
userRawData: 1